### ISSUE TITLE
Minor Paper Draft Notes and Comments

### ISSUE THREAD

**Issue by eghuang** [eghuang/NASAmouseHG#5]
Quoted from Ray:
> Writing papers for Radiobiologists. A sub-project that is strictly optional, potentially very time consuming, very instructive both per se and for understanding our eventual paper in detail, very useful to me, and subject to repeated revisions as the paper evolves.

> Just uploaded a .pdf useful in writing a first draft of the Methods section for Edward (and if Yimin wants I will adapt the .pdf to include instructions for him to work on writing a first draft of the start of the Results section). As time permits [Edward] will try to write a first draft of the mathematical methods section of the paper.

Here we will guide the development of the first draft of our manuscript. As of now I have been assigned the Methods section and Ray will work on the rest. Relevant materials and drafts for the paper will be stored in the `paper` folder of this repository. My portion of the draft, `drafts.Rmd`, is written in R Markdown and will be rendered to a .pdf `drafts.pdf`. These assignments and file locations may be subject to change.

Future in-depth discussion of the draft and edits should be kept primarily to this thread.

**Comment by rainersachs** [comment]
Edward: I just downloaded a cryptic writing assignment in the (unlikely) even you have extra time this coming week in addition to your midterms. It is to fill in 2.1 in my  uploaded .docx file and skim 2.2 and 2.3. However 2.2 and 2.3 will probably be pretty incomprehensible until I have a chance to explain them Thursday, so don't worry if some parts are just too obscure. I assume that if you do have time to write anything it will appear as a .pdf made with Latex or any other editor convenient for you.

**Comment by rainersachs** [comment]
[YiminWeekofOctober22_2017.pdf](https://github.com/eghuang/NASAmouseHG/files/1408804/YiminWeekofOctober22_2017.pdf)

Hi! is this .pdf of figure corrections readable. If not can I put the .pdf somewhere else on GitHub. If not I'll send by email

**Comment by yiminllin** [comment]
Received! It is readable. I will make the corrections over this week.

**Comment by rainersachs** [comment]
starting .Rmd for supplement

**Comment by rainersachs** [comment]
Here are updated .pdfs of the minor paper and its web supplement for the journal web site. .docx versions are available from Sachs by email.
[MS05.docx](https://github.com/eghuang/NASAmouseHG/files/1764201/MS05.docx)
[ESM_Online_Resource_1.docx](https://github.com/eghuang/NASAmouseHG/files/1764203/ESM_Online_Resource_1.docx)

[ESM_Online_Resource_1.pdf](https://github.com/eghuang/NASAmouseHG/files/1764157/ESM_Online_Resource_1.pdf)

[MS05.pdf](https://github.com/eghuang/NASAmouseHG/files/1764146/MS05.pdf)

**Comment by rainersachs** [comment]
Hi Edward: A minor point is the following. I thought I should download these files to the folder on minor papers but to my surprise was not able to. Is that normal? Instead I was only able to download them to this issue on the minor paper. That serves the purpose so no need for you to do anything.

**Comment by eghuang** [comment]
The manuscript has been submitted and accepted for publication.
